name: Release
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      # - name: Build and test
      #   run: python setup.py build && python -m unittest discover
      # - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Add comments
        uses: actions/github-script@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const releaseId = steps.create_release.outputs.release_id;
            const release = await context.github.repos.getRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: releaseId
            });
            context.github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: release.data.number,
              body: 'This release contains the following changes: \n - Feature A \n - Bugfix B \n - Performance improvements'
            });
